TEMPLATE_MENU = "menu-template"
TEMPLATE_MAIN_MAP = "main-map-template"
TEMPLATE_INSIDE_POKESTOP = "inside-pokestop-template"
TEMPLATE_CLEAR_BAG = "clear-bag"

MIN_RECOGNITION_VAL = 0.01 #if we get below that value indicates that we found template

DEL_ITEMS_POKEYBALL=1
DEL_ITEMS_RAZZ_BERRY=2
DEL_ITEMS_NANAB_BERRY=4
DEL_ITEMS_POTION=8
DEL_ITEMS_REVIVE=16


SCREEN_MAIN_MAP = 1
SCREEN_MAIN_MENU = 2
SCREEN_INSIDE_POKESTOP = 3

MESSAGE_ANDROID_TYPE_TEST = 1
MESSAGE_ANDROID_SCREEN_CAP = 2
MESSAGE_ANDROID_SEND_TOUCH = 3
MESSAGE_ANDROID_SEND_SWIPE = 4